In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
import pandas as pd

In [17]:
import numpy as np

In [18]:
print "hello world"

hello world


In [5]:
prases = ["I am going to have a pizza dilivered for dinner",
          "I am going to try that new French restaurant for dinner",
          "I prefer reading over going to movie",
          "I prefer going to the movies over reading books",
          "I have friends in New York city",
          "She loves going to movies"]

In [7]:
vect = TfidfVectorizer(min_df=1)
tfidf = vect.fit_transform(prases)

In [8]:
cosine = (tfidf*tfidf.T).A

In [9]:
print cosine

[[ 1.          0.414471    0.12214428  0.1006697   0.12736866  0.12856247]
 [ 0.414471    1.          0.10384321  0.0855862   0.10828481  0.10929975]
 [ 0.12214428  0.10384321  1.          0.59151203  0.          0.15598707]
 [ 0.1006697   0.0855862   0.59151203  1.          0.          0.29323951]
 [ 0.12736866  0.10828481  0.          0.          1.          0.        ]
 [ 0.12856247  0.10929975  0.15598707  0.29323951  0.          1.        ]]


In [10]:
df = pd.DataFrame(cosine, index=prases, columns=prases)

In [11]:
df

I am going to have a pizza dilivered for dinner  \
I am going to have a pizza dilivered for dinner                                            1.000000   
I am going to try that new French restaurant fo...                                         0.414471   
I prefer reading over going to movie                                                       0.122144   
I prefer going to the movies over reading books                                            0.100670   
I have friends in New York city                                                            0.127369   
She loves going to movies                                                                  0.128562   

                                                    I am going to try that new French restaurant for dinner  \
I am going to have a pizza dilivered for dinner                                              0.414471         
I am going to try that new French restaurant fo...                                           1.000000         
I prefer reading over going to movie                                                         0.103843         
I prefer going to the movies over reading books                                              0.085586         
I have friends in New York city                                                              0.108285         
She loves going to movies                                                                    0.109300         

                                                    I prefer reading over going to movie  \
I am going to have a pizza dilivered for dinner                                 0.122144   
I am going to try that new French restaurant fo...                              0.103843   
I prefer reading over going to movie                                            1.000000   
I prefer going to the movies over reading books                                 0.591512   
I have friends in New York city                                                 0.000000   
She loves going to movies                                                       0.155987   

                                                    I prefer going to the movies over reading books  \
I am going to have a pizza dilivered for dinner                                            0.100670   
I am going to try that new French restaurant fo...                                         0.085586   
I prefer reading over going to movie                                                       0.591512   
I prefer going to the movies over reading books                                            1.000000   
I have friends in New York city                                                            0.000000   
She loves going to movies                                                                  0.293240   

                                                    I have friends in New York city  \
I am going to have a pizza dilivered for dinner                            0.127369   
I am going to try that new French restaurant fo...                         0.108285   
I prefer reading over going to movie                                       0.000000   
I prefer going to the movies over reading books                            0.000000   
I have friends in New York city                                            1.000000   
She loves going to movies                                                  0.000000   

                                                    She loves going to movies  
I am going to have a pizza dilivered for dinner                      0.128562  
I am going to try that new French restaurant fo...                   0.109300  
I prefer reading over going to movie                                 0.155987  
I prefer going to the movies over reading books                      0.293240  
I have friends in New York city                                      0.000000  
She loves going to movies                                            1.000000

In [19]:
import seaborn as sns
%matplotlib inline

ImportError: No module named seaborn

In [20]:
from sklearn.decomposition import NMF

In [21]:
d1 = open("tfidf_1.txt").read()
d2 = open("tfidf_2.txt").read()
d3 = open("tfidf_3.txt").read()
d4 = open("tfidf_4.txt").read()
d5 = open("tfidf_5.txt").read()
d6 = open("tfidf_6.txt").read()
d7 = open("tfidf_7.txt").read()
d8 = open("tfidf_8.txt").read()
d9 = open("tfidf_9.txt").read()
d10 = open("tfidf_10.txt").read()

In [22]:
dataset = [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10]

In [23]:
vectorizer = TfidfVectorizer(min_df = 1, max_features = 100, stop_words = "english")

In [24]:
tfidf = vectorizer.fit_transform(dataset)

In [25]:
nmf = NMF(n_components=10, random_state=1).fit(tfidf)

In [26]:
feature_names = vectorizer.get_feature_names()

In [29]:
for topic_idx, topic in enumerate(nmf.components_):
    print("Topic #%d:" %topic_idx)
    print " ".join([feature_names[i]
                   for i in topic.argsort()[:-10 -1:-1]])
    print "\n"

Topic #0:
revolution french revolutionary napoleon political leading global popular modern republic


Topic #1:
tesla electrical wireless work york popular new power american series


Topic #2:
newton work earth time day later european president church government


Topic #3:
leonardo man time later widely world life history april france


Topic #4:
lunar module armstrong apollo earth landed command july 11 man


Topic #5:
rockefeller oil church life american modern man national supported central


Topic #6:
war soviet union axis germany allies japan united invasion 1945


Topic #7:
titanic ship passengers safety people april new wireless world led


Topic #8:
washington american president british continental national army united states war


Topic #9:
napoleon french coalition europe france battle empire military army allies


